FROM eclipse/node
RUN cd $HOME && git clone https://github.com/theia-ide/theia
RUN sudo apt-get update
RUN sudo apt-get install -y python
RUN cd $HOME/theia && npm install --no-optional
RUN cd $HOME/theia && cd config/local-dependency-manager && npm install && cd ../../examples/browser && npm run bootstrap
CMD cd $HOME/theia/examples/browser && (node ./lib/backend/main.js --root-dir=/projects &) && npm run start:frontend

LABEL che:server:3000:ref=theia che:server:3000:protocol=http

EXPOSE 4403 8080 8000 22
LABEL che:server:8080:ref=tomcat8 che:server:8080:protocol=http che:server:8000:ref=tomcat8-debug che:server:8000:protocol=http


ENV MAVEN_VERSION=3.3.9 \
    TOMCAT_HOME=/home/user/tomcat8

ENV M2_HOME=/home/user/apache-maven-$MAVEN_VERSION

ENV PATH=$M2_HOME/bin:$PATH

RUN mkdir /home/user/cbuild /home/user/tomcat8 /home/user/apache-maven-$MAVEN_VERSION && \
  wget -qO- "http://apache.ip-connect.vn.ua/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz" | tar -zx --strip-components=1 -C /home/user/apache-maven-$MAVEN_VERSION/

ENV TERM xterm

RUN wget -qO- "http://archive.apache.org/dist/tomcat/tomcat-8/v8.0.24/bin/apache-tomcat-8.0.24.tar.gz" | tar -zx --strip-components=1 -C /home/user/tomcat8 && \
    rm -rf /home/user/tomcat8/webapps/* && \
    echo "export MAVEN_OPTS=\$JAVA_OPTS" >> /home/user/.bashrc
